import Head from "next/head";
import Container from "../components/navigation/Container";
import styled from "styled-components";
import PrincipalHome from "../components/home/Principal";

const PrincipalPage = styled.div`
  background-color: #296281;
  min-height: 100vh;
`;
const Title = styled.h1`
  color: white;
  text-align: center;
  padding: 50px 10px;
  font-family: "Lucida Sans", "Lucida Sans Regular", "Lucida Grande",
    "Lucida Sans Unicode", Geneva, Verdana, sans-serif;
`;

export default function Home() {
  return (
    <PrincipalPage>
      <Head>
        <title>Zebrands-Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/zebrand.ico" />
      </Head>
      <Container>
        <Title>Search GitHub User</Title>
        <PrincipalHome />
      </Container>
    </PrincipalPage>
  );
}
