/* eslint-disable react/no-unescaped-entities */
import Head from "next/head";
import styled from "styled-components";
import Container from "../components/navigation/Container";
import UsersList from "../components/users/Users";

const UserPage = styled.div`
  display: flex;
  background-color: #145385;
`;

const Title = styled.h1`
  color: #fd6d6d;
  text-align: center;
  padding: 20px 0;
  font-weight: 900;
  font-family: "Lucida Sans", "Lucida Sans Regular", "Lucida Grande",
    "Lucida Sans Unicode", Geneva, Verdana, sans-serif;
`;

const Users = () => {
  return (
    <UserPage>
      <Head>
        <title>Zebrands-Users</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/zebrand.ico" />
      </Head>
      <Container>
        <Title>GitHub User's List</Title>
        <UsersList />
      </Container>
    </UserPage>
  );
};

export default Users;
